-- 표시광고 "뒷광고 의심" 자동 모니터링 — 스캔 후보 저장 테이블
--   Edge Function `ad-watch-scan`이 네이버 검색 API로 후보를 찾고,
--   본문을 가져와 Claude로 1차 판별한 결과를 저장한다.
--   사람이 검수해서 '적발등록'(records에 실제 반영) 또는 '오탐제외' 처리.
--
-- 적용 방법:
--   Supabase 대시보드 → SQL Editor → 본 SQL 실행
--   (또는 CLI: supabase db push)
--   실행 후 records 테이블과 동일 수준의 RLS 정책을 콘솔에서 확인/설정할 것.

create table if not exists ad_watch_candidates (
  id bigint generated by default as identity primary key,
  scan_id bigint not null,              -- 한 번의 스캔 실행을 묶는 값(Edge Function 시작 시각 ms)
  period_from date not null,
  period_to date not null,
  brand text not null,
  platform text not null,               -- '네이버블로그' | '네이버카페'
  title text not null,
  link text not null,
  snippet text,
  blogger_name text,
  post_date date,
  body_fetch_ok boolean not null default false,  -- 본문 수집 성공 여부(실패 시 스니펫만으로 판별)
  image_count integer not null default 0,        -- 비전 분석에 실제로 사용된 이미지 수
  ai_verdict text,                      -- '의심' | '주의' | '낮음' | null(미분류)
  ai_reason text,
  status text not null default '검토대기',       -- '검토대기' | '적발등록' | '오탐제외'
  linked_record_id bigint,              -- '적발 등록' 시 생성된 records.id
  reviewed_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_ad_watch_candidates_status on ad_watch_candidates(status);
create index if not exists idx_ad_watch_candidates_scan_id on ad_watch_candidates(scan_id);
